server:
  port: 8080

spring:
  freemarker:
    charset: UTF-8
    check-template-location: true
    suffix: .ftl
    #### debug环境使用
    cache: false
    template-loader-path:
      - classpath:/templates/

  datasource:
    url: jdbc:mysql://localhost:3306/zeus?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: debian-sys-maint
    password: OWHUxKOQNitQhnRb
#  webflux:
#    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:log4j2-spring.xml

